// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEGb9xvAeOwWMqq_hQnMjHFFe8LfwBmQQ',
    appId: '1:545598783308:web:db31748d8a967e67ba19e9',
    messagingSenderId: '545598783308',
    projectId: 'health-app-a9d2a',
    authDomain: 'health-app-a9d2a.firebaseapp.com',
    storageBucket: 'health-app-a9d2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClkzYizpQ8bObEZxPH3FHlsdvodzfZisk',
    appId: '1:545598783308:android:f0ac2b47c8af7978ba19e9',
    messagingSenderId: '545598783308',
    projectId: 'health-app-a9d2a',
    storageBucket: 'health-app-a9d2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJE7rSOaDVKnlzT7SVMmmzZWnu1sHjlg',
    appId: '1:545598783308:ios:5bfddc2b962d5119ba19e9',
    messagingSenderId: '545598783308',
    projectId: 'health-app-a9d2a',
    storageBucket: 'health-app-a9d2a.appspot.com',
    iosBundleId: 'com.example.healthApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJE7rSOaDVKnlzT7SVMmmzZWnu1sHjlg',
    appId: '1:545598783308:ios:5bfddc2b962d5119ba19e9',
    messagingSenderId: '545598783308',
    projectId: 'health-app-a9d2a',
    storageBucket: 'health-app-a9d2a.appspot.com',
    iosBundleId: 'com.example.healthApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEGb9xvAeOwWMqq_hQnMjHFFe8LfwBmQQ',
    appId: '1:545598783308:web:7b09d60c8286452bba19e9',
    messagingSenderId: '545598783308',
    projectId: 'health-app-a9d2a',
    authDomain: 'health-app-a9d2a.firebaseapp.com',
    storageBucket: 'health-app-a9d2a.appspot.com',
  );
}
